name = "cloudpass-backend"
main = "src/index.js"
compatibility_date = "2023-10-30"

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
ENCRYPTION_KEY = "your-encryption-key"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[[r2_buckets]]
binding = "R2"
bucket_name = "your-r2-bucket"
